// <auto-generated />
using System;
using EasyWeChat.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyWeChat.Domain.Migrations
{
    [DbContext(typeof(EasyWeChatDbContext))]
    partial class EasyWeChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EasyWeChat.Domain.Entities.ApplyInfo", b =>
                {
                    b.Property<long>("ApplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ApplyMessage")
                        .HasColumnType("varchar(50)");

                    b.Property<long>("ApplyUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<long>("ContanctId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastApplyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ReceiveUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ApplyId");

                    b.ToTable("ApplyInfos");
                });

            modelBuilder.Entity("EasyWeChat.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<double>("FileSize")
                        .HasColumnType("double");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<string>("MessageContent")
                        .HasColumnType("longtext");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("SendUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("SendUserNickName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("EasyWeChat.Domain.Entities.ChatSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastReceviceTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SessionId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("EasyWeChat.Domain.Entities.ChatSessionUser", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastReceiveTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "ContactId", "ContactType");

                    b.ToTable("ChatSessionUsers");
                });

            modelBuilder.Entity("EasyWeChat.Domain.Entities.GroupInfo", b =>
                {
                    b.Property<long>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GroupNotice")
                        .HasColumnType("varchar(200)");

                    b.Property<long>("GroupOwnerId")
                        .HasColumnType("bigint");

                    b.Property<int>("JoinType")
                        .HasColumnType("int");

                    b.Property<string>("PicExtension")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.ToTable("GroupInfos");
                });

            modelBuilder.Entity("EasyWeChat.Domain.Entities.UserContact", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<int>("ContanctType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ContactId");

                    b.ToTable("UserContacts");
                });

            modelBuilder.Entity("EasyWeChat.Domain.Entities.UserInfo", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AreaCode")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AreaName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("JoinType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastOffTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PicExtension")
                        .HasColumnType("longtext");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
